# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3cgvHH9SxqGyfsBlL0fNyK-WU4iNhk7
"""

import numpy as np

#Creating Array
arr=np.array([6,3,7,1,9,7])
print(arr)


#Array indexing
arr=np.array([6,3,7,1,9,7])
print(arr[0])
print(arr[3])


#Array Slicing
arr=np.array([3,5,6,7,3,8,3,5,0,1,7,1])
print(arr[2:8])


#Join array
arr1=np.array([6,3,9,1,7])
arr2=np.array([4,6,9,2,5])
arr=np.concatenate((arr1,arr2))
print(arr)


#Array Split
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr)


#Array Search
arr = np.array([1, 7, 5, 4, 7, 7, 3])
x = np.where(arr == 7)
print(x)